import { readFileSync, writeFileSync } from "node:fs";
import idContinue from "@unicode/unicode-17.0.0/Binary_Property/ID_Continue/code-points.js";
import idStart from "@unicode/unicode-17.0.0/Binary_Property/ID_Start/code-points.js";

const outputPath = new URL("../common/javascript/unicode.js", import.meta.url);

function characterClass(codePoints) {
  const ranges = [];
  for (const codePoint of codePoints.toSorted((left, right) => left - right)) {
    const previous = ranges.at(-1);
    if (previous && codePoint === previous[1] + 1) previous[1] = codePoint;
    else ranges.push([codePoint, codePoint]);
  }
  const codePointEscape = (value) => `\\u{${value.toString(16)}}`;
  return `[${ranges
    .map(([first, last]) =>
      first === last
        ? codePointEscape(first)
        : `${codePointEscape(first)}-${codePointEscape(last)}`,
    )
    .join("")}]`;
}

function generateUnicode() {
  return [
    "// Generated by scripts/generate-unicode.js; do not edit.",
    "// Unicode data: @unicode/unicode-17.0.0; notice: LICENSE-UNICODE.",
    `export const unicodeIdStart = ${JSON.stringify(characterClass(idStart))};`,
    `export const unicodeIdContinue = ${JSON.stringify(characterClass(idContinue))};`,
    "",
  ].join("\n");
}

function main(arguments_) {
  if (
    arguments_.length > 1 ||
    (arguments_.length === 1 && arguments_[0] !== "--check")
  ) {
    throw new Error("Usage: node scripts/generate-unicode.js [--check]");
  }
  const generated = generateUnicode();
  if (arguments_.length === 0) {
    writeFileSync(outputPath, generated);
    return 0;
  }
  let actual;
  try {
    actual = readFileSync(outputPath, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (actual !== generated) {
    throw new Error(
      "Generated Unicode classes are stale or missing; run node scripts/generate-unicode.js",
    );
  }
  return 0;
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
